// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "CytoML_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// setCounts
void setCounts(Rcpp::XPtr<GatingSet> gsPtr, string sampleName, string node, int count);
RcppExport SEXP _CytoML_setCounts(SEXP gsPtrSEXP, SEXP sampleNameSEXP, SEXP nodeSEXP, SEXP countSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<GatingSet> >::type gsPtr(gsPtrSEXP);
    Rcpp::traits::input_parameter< string >::type sampleName(sampleNameSEXP);
    Rcpp::traits::input_parameter< string >::type node(nodeSEXP);
    Rcpp::traits::input_parameter< int >::type count(countSEXP);
    setCounts(gsPtr, sampleName, node, count);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CytoML_setCounts", (DL_FUNC) &_CytoML_setCounts, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CytoML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
