# Generated by cpp11: do not edit by hand

setLogLevel <- function(loglevel) {
  invisible(.Call(`_CytoML_setLogLevel`, loglevel))
}

open_workspace <- function(filename, sample_name_location, xmlParserOption) {
  .Call(`_CytoML_open_workspace`, filename, sample_name_location, xmlParserOption)
}

parse_workspace <- function(ws, group_id, subset, execute, path, cytoset, backend_dir, backend, includeGates, additional_keys, additional_sampleID, keywords, is_pheno_data_from_FCS, keyword_ignore_case, extend_val, extend_to, channel_ignore_case, leaf_bool, include_empty_tree, skip_faulty_gate, comps, transform, fcs_file_extension, greedy_match, fcs_parse_arg, num_threads) {
  .Call(`_CytoML_parse_workspace`, ws, group_id, subset, execute, path, cytoset, backend_dir, backend, includeGates, additional_keys, additional_sampleID, keywords, is_pheno_data_from_FCS, keyword_ignore_case, extend_val, extend_to, channel_ignore_case, leaf_bool, include_empty_tree, skip_faulty_gate, comps, transform, fcs_file_extension, greedy_match, fcs_parse_arg, num_threads)
}

get_keywords_by_id <- function(ws, sample_id) {
  .Call(`_CytoML_get_keywords_by_id`, ws, sample_id)
}

get_keywords_by_name <- function(ws, sample_name) {
  .Call(`_CytoML_get_keywords_by_name`, ws, sample_name)
}

get_sample_groups <- function(ws) {
  .Call(`_CytoML_get_sample_groups`, ws)
}

get_samples <- function(ws) {
  .Call(`_CytoML_get_samples`, ws)
}

get_xml_file_path <- function(ws) {
  .Call(`_CytoML_get_xml_file_path`, ws)
}
