# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

append_sample_node <- function(gs, sn, sampleId, show_hidden) {
    .Call(`_cytoml2_append_sample_node`, gs, sn, sampleId, show_hidden)
}

append_keywords_node <- function() {
    .Call(`_cytoml2_append_keywords_node`)
}

append_derived_params_node <- function(outputdir) {
    .Call(`_cytoml2_append_derived_params_node`, outputdir)
}

append_transformation_node <- function() {
    .Call(`_cytoml2_append_transformation_node`)
}

append_spillover_matrix_node <- function(gs, sn) {
    .Call(`_cytoml2_append_spillover_matrix_node`, gs, sn)
}

open_workspace <- function(filename, sample_name_location, xmlParserOption) {
    .Call(`_cytoml2_open_workspace`, filename, sample_name_location, xmlParserOption)
}

parse_workspace <- function(ws, group_id, subset, execute, path, h5_dir, includeGates, additional_keys, additional_sampleID, keywords, is_pheno_data_from_FCS, keyword_ignore_case, extend_val, extend_to, channel_ignore_case, leaf_bool, comps, transform, fcs_file_extension, fcs_parse_arg, num_threads = 1L) {
    .Call(`_cytoml2_parse_workspace`, ws, group_id, subset, execute, path, h5_dir, includeGates, additional_keys, additional_sampleID, keywords, is_pheno_data_from_FCS, keyword_ignore_case, extend_val, extend_to, channel_ignore_case, leaf_bool, comps, transform, fcs_file_extension, fcs_parse_arg, num_threads)
}

get_keywords_by_id <- function(ws, sample_id) {
    .Call(`_cytoml2_get_keywords_by_id`, ws, sample_id)
}

get_keywords_by_name <- function(ws, sample_name) {
    .Call(`_cytoml2_get_keywords_by_name`, ws, sample_name)
}

get_sample_groups <- function(ws) {
    .Call(`_cytoml2_get_sample_groups`, ws)
}

get_samples <- function(ws) {
    .Call(`_cytoml2_get_samples`, ws)
}

get_xml_file_path <- function(ws) {
    .Call(`_cytoml2_get_xml_file_path`, ws)
}

